version: '3'

#環境によってselinuxでパーミッションエラーが出るのでvolumesの最後に:zが必要(Fodora28)

services:
  php:
      build:
        context: .\php
      container_name: "news-map"
      ports:
        - 80:80
      volumes:
        - .\src:/var/www/news-map:z
      links:
        - redis

  redis:
      restart: always
      image: redis